config/routes.rb
EvilHangman2::Application.routes.draw do
  controller :sessions do
    get 'login' => :new
    get 'loginNew' => :create
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :game do
    get 'hangman' => :hangman
    get 'save_history' => :save_history
  end

  get 'playAnonymously' => 'users#createAnon'

  resources :users
  resources :history_entries

  root :to => 'game#index', :as => 'game'

end

app/models/user.rb
require'digest/sha2'

class User < ActiveRecord::Base
  validates :username, :password, :presence => true
  validates :username, :uniqueness => true

  validates :password, :confirmation => true
  validates :password, :length => {
      :minimum => 5
  }
  attr_accessor :password_confirmation
  attr_reader  :password
  validate :password_must_be_present

  attr_accessible :username, :password, :password_confirmation, :profile_image_url, :user_type

  has_many :history_entries, :dependent => :destroy

  def User.authenticate(username, password)
    if user = find_by_username(username)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end

  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private
    def password_must_be_present
      errors.add(:password, "Missing Password") unless hashed_password.present?
    end

    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create, :createAnon, :destroy, :show, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:username)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])


    respond_to do |format|
      if @user.save
        format.html{ redirect_to(loginNew_url(:username => @user.username, :password => @user.password)) }
        #format.html { redirect_to(game_url, notice: "User #{@user.username} successfully created.") }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url, notice: "User #{@user.username} was successfully updated.") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  # GET /users/playAnonymously
  def createAnon
    @user = User.new({:username => "Anon#{Time.now.to_s}", :password => "anonymous", :password_confirmation => "anonymous", :profile_image_url => "", :user_type => 1})

    respond_to do |format|
      if @user.save
        format.html{ redirect_to(loginNew_url(:username => @user.username, :password => @user.password)) }
        #format.html { redirect_to(game_url, notice: "User #{@user.username} successfully created.") }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user account from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter your information and click save to start playing!</legend>
    <div class="row">
      <div class="span6">
        <span class="label label-info">Username</span>
        <%= f.text_field :username, :size => 40 %>
      </div>
      <div class="span6">
        <span class="label label-info">Image url (not required)</span>
        <%= f.text_field :profile_image_url %>
      </div>

    </div>
    <div class="row">
      <div class="span6">
        <span class="label label-info">Password</span>
        <%= f.password_field :password, :size => 40 %>
      </div>

      <div class="span6">
          <span class="label label-info">Confirm Password</span>
          <%= f.password_field :password_confirmation, :size => 40 %>
      </div>


     </div>

      <div>
        <%=  f.submit %>
      </div>

  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Game History</h1>
    <% if notice %>
        <p id="notice"><%= notice %></p>
    <% end %>

<div class="container">
  <div class="row">
    <div class="span8">
<table class="table table-condensed table-hover table-striped">
  <tr>
    <th>Profile Image</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%=
            if user.profile_image_url.length > 0
              image_tag(user.profile_image_url, :class =>'list_image')
            else
              "none"
            end
        %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
    </div>

    <div class="span4">
      <div class="row">
        <div class="span2">
          High Score:
        </div>
        <div class="span2">
          10,000
        </div>
      </div>
    </div>
  </div>
</div>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Create your Evil Hangman account</h1>
  <em>Enter your information and click save to start playing!</em>
</div>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user account from being saved:</h4>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<fieldset>

  <div class="row">
    <div class="span6">
      <span class="label label-info">Username</span><br/><br/>
      <%= f.text_field :username, :size => 40 %><br/><br/>
    </div>
    <div class="span6">
      <span class="label label-info">Image Url (Not Required)</span><br/><br/>
      <%= f.text_field :profile_image_url %><br/><br/>
    </div>

  </div>
  <div class="row">
    <div class="span6">
      <span class="label label-info">Password</span><br/><br/>
      <%= f.password_field :password, :size => 40 %><br/><br/>
    </div>

    <div class="span6">
      <span class="label label-info">Confirm Password</span><br/><br/>
      <%= f.password_field :password_confirmation, :size => 40 %><br/><br/>
    </div>

  </div>

  <div class="row">
    <div class="span6">
      <%= link_to 'Back', game_path, :class=> "btn btn-info "%>
    </div>
    <div class="span6">
      <%= submit_tag "Save", :class=> "btn btn-info "%>
    </div>
  </div>

</fieldset>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Profile image url:</b>
  <%= @user.profile_image_url %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>